# **NUMPY**

In [ ]:
import numpy as np  #import Numpy

array_hai_bhai = np.array ([1,2,3,4,5,6,7,8])  #declare an Array
array_hai_bhai

array_hai_bhai = np.array ([1,2,3,4,5,6,7,8],np.int8)  ##can show input of 8 between them
array_hai_bhai

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

In [ ]:
matrix = np.zeros([3,3])  #print all the zeros Matrix of 3x3
print(matrix)

matrix = np.ones([3,3])  #print all the Ones Matrix of 3x3
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
matrix = np.arange(4,20,2)  #Create Array 4 to 20 with steps 2
print(matrix)

matrix = np.linspace(4,20,5)  #Divides the Range 4-20 into Steps Given 5
print(matrix)

[ 4  6  8 10 12 14 16 18]
[ 4.  8. 12. 16. 20.]


In [ ]:
array_hai_bhai = np.array ([1,2,3,4,5,6,7,8])  #declare an Array
array_hai_bhai
array_hai_bhai[3]   #Index the 3
array_hai_bhai[2:7]   #Index the 2--7

array([3, 4, 5, 6, 7])

In [ ]:
array_hai_bhai = np.array ([1,2,3,4,5,6,4,8,5,21,43,54,12,43,56,756])  #declare an Array
shape = array_hai_bhai.reshape(4,4)   #Convert 1D into 2D Array
shape

OneD = shape.flatten() #Again Convert 2D into 1D Array
OneD

array([  1,   2,   3,   4,   5,   6,   4,   8,   5,  21,  43,  54,  12,
        43,  56, 756])

In [ ]:
OneD = shape.ravel() #Convert into 1D Array
OneD

array([  1,   2,   3,   4,   5,   6,   4,   8,   5,  21,  43,  54,  12,
        43,  56, 756])

In [ ]:
#Works on Functions like np.sum(), np.mean(), np.min(), np.max(), np.std(), etc.
array_hai_bhai = np.array ([2,3,4,5,6,4,8,5,21])

print(array_hai_bhai + 2) #adding 2 to Each Number
print(array_hai_bhai * 5) #Multiplying 2 to Each Number

print(np.sum(array_hai_bhai))   #to find SUM
print(np.mean(array_hai_bhai))  #to find MEAN
print(np.max(array_hai_bhai))  #to find MAX
print(np.min(array_hai_bhai)) #to find MIN
print(np.std(array_hai_bhai)) #to find STD
print(np.sqrt(array_hai_bhai))  #to find SQRT

[ 4  5  6  7  8  6 10  7 23]
[ 10  15  20  25  30  20  40  25 105]
58
6.444444444444445
21
2
5.397759022884942
[1.41421356 1.73205081 2.         2.23606798 2.44948974 2.
 2.82842712 2.23606798 4.58257569]


In [ ]:
#Multiply and Inverse the Matrix
Matrix1 = np.array([[5,7],[7,9]])
Matrix2 = np.array([[4,6],[5,9]])

Product = np.matmul(Matrix1,Matrix2) #Multiply the 2 Matrics
print(Product)

Inverse = np.linalg.inv(Matrix2) #Inverse any 1 Matrix
print(Inverse)

[[ 55  93]
 [ 73 123]]
[[ 1.5        -1.        ]
 [-0.83333333  0.66666667]]


In [ ]:
#Random Number Generator
my_random = np.random.randn(2,15)  #2 random values Matrics of 15,15
print(my_random)

[[ 0.99875678 -0.07549348  1.09815643 -1.94845145 -1.49452633  0.06971458
  -0.27568299  1.28725035 -0.88337016  0.95211008 -0.05779786 -0.89506835
  -0.50574118 -1.30321663 -0.51268544 -0.29028376  0.4097379   2.18785948
   1.55591222  1.3362305   1.060307    1.30695871  0.93452823  0.30746554
   0.59360572 -1.42628421 -0.46982466 -0.43572388 -1.54598331  0.02830042
   0.57321772  0.86748814 -0.1759038   0.97579038  0.96491085 -0.65691887
  -0.34482596 -0.00924215  1.52794593  0.03752114  0.68687132 -1.6178475
  -0.44511981 -0.06333617 -0.13292482  1.17379241 -0.64999649  0.66256136
   0.03479416  0.58557827]
 [ 1.63906233  1.86681683  1.56905835 -0.37381742  0.47737544 -0.19454358
  -0.35538439  1.56943797  0.36831214  0.66236134 -0.05844637 -0.15389603
   0.39046327 -0.25477706  1.71575004  0.78048951 -2.10917066  0.32105306
   0.09729851  1.12373139 -1.09953404  0.68581967 -0.56721302 -0.07410925
   0.47223151 -0.2038382  -1.24616294  0.13662345  1.30265143 -1.11493832
  -0.2974687

In [ ]:
#Another random Number
my_random = np.random.randint(1,100) #Generate Random Number
myy_random = np.random.randint(1,100, size=[3,5]) #Matrix 3,5 from Values 1-100
print(my_random)
print(myy_random)

2
[[ 3 66 47 67 36]
 [79 56 98 25 98]
 [38 18  3 73 58]]


In [ ]:
#Broadcasting or Scaler
my_random = np.random.randint(1,50, size=[2,2])
scaler = 2

result = my_random * scaler
print(result)

[[28 62]
 [92 56]]


In [ ]:
array_hai_bhai = np.array ([[1,2,3,4,5,6,7,8]])  #declare an Array
array_hai_bhai[0,4] #0 column par 4th Index

5

In [ ]:
array_hai_bhai.shape #There is 1 Row 8 Columns
# array_hai_bhai.dtype  #tells the d type

(1, 8)

In [ ]:
array_hai_bhai[0,3] = 99  #Replace 3d index by 99
array_hai_bhai


array([[ 1,  2,  3, 99,  5,  6,  7,  8]])

In [ ]:
emp = np.empty((3,5)) #Generates Random Values Array Empty
emp

array([[1.19e-322, 9.88e-323, 1.28e-322, 3.71e-322, 1.68e-322],
       [3.61e-322, 4.59e-322, 4.55e-322, 3.71e-322, 2.27e-322],
       [3.11e-322, 3.11e-322, 3.90e-322, 3.31e-322, 4.45e-322]])

In [ ]:
ide = np.identity(45) #Make identty Matrics 45 BY 45
ide
# ide.shape

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
Matrix = np.array([[5,7],[7,9],[6,8]])

Product = Matrix.sum(axis=0) #Sum all the columns Wise 5+7+6
print(Product)
Product = Matrix.sum(axis=1) #Sum all the Rows Wise 5+7+6
print(Product)

[18 24]
[12 16 14]


In [ ]:
Matrix = np.array([[5,7],[7,9],[6,8]])
Matrix.T  #Take Transpose

array([[5, 7, 6],
       [7, 9, 8]])

In [ ]:
for x in Matrix.flat: #flat gives the Whole Number Integers
  print(x)

5
7
7
9
6
8


In [ ]:
Matrix.ndim #Dimenstions
Matrix.size #No of Elements in Matric
Matrix.nbytes #Bytes
array_hai_bhai = np.array ([1,2,3,4,5,6,7,8])  #declare an Array
array_hai_bhai.argmax() #index of Maximum Elements

7

In [ ]:
array_hai_bhai = np.array ([1,2,7,4,3,4,9,1])  #declare an Array
array_hai_bhai.argsort() #Tell indexes on Whixh if Elements are, they Sorted

array([0, 7, 1, 4, 3, 5, 2, 6])

In [ ]:
Matrix = np.array([[5,7],[7,9],[6,8]])
Matrix
Matrix.argmax(axis=0) #where is the Max Element in all Columns
Matrix.argsort(axis=0) #where is the Max Element in all Columns

array([[0, 0],
       [2, 2],
       [1, 1]])

In [ ]:
Matrix = np.array([[5,7] ,[7,9],[6,8]])
Matrix
np.where(Matrix>7) #tells where is Greater than 7

(array([1, 2]), array([1, 1]))

In [ ]:
import sys

In [ ]:
py_arr = [3,4,5,68,76,34,43,2,543,43] #Simple Python Array
np_arr = np.array(py_arr) #Using Numpy Array

sys.getsizeof(1) * len(py_arr)   #Size of Simple Array

280

In [ ]:
np_arr.itemsize * np_arr.size  #Size of Numpy Array

80

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4) #Split the Array into 4 Parts
newarr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [ ]:
np.sort(np_arr)   #Sorted the 1D Array

array([  2,   3,   4,   5,  34,  43,  43,  68,  76, 543])

In [ ]:
arr = np.array([41, 42, 43, 44])  #Filter an Array

filter_arr = arr > 42
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


# **Pandas**

In [ ]:
print("Hi PANDAS BYE NUMPY 😍")

Hi PANDAS BYE NUMPY 😍


In [ ]:
pip install pandas

In [ ]:
import pandas as pd

data = {
    "Name": ["Ali","Anjum","Shoaib","Raja"],  #Sets the Data
    "Age": [23,21,25,15],
    "Grade": ['A','F','D','C']

}

df = pd.DataFrame(data) #Make DataFrame Excel like Columns
df

Name  Age Grade
0     Ali   23     A
1   Anjum   21     F
2  Shoaib   25     D
3    Raja   15     C

In [ ]:
# df = pd.read_csv('file.csv')
# df = pd.read_excel('file.xlsx')

In [ ]:
df.head() #Show first 5 Columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   Grade   4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [ ]:
df.info() #Show Data-Structures

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   Grade   4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [ ]:
print(df.describe()) #If Needs the Description

             Age
count   4.000000
mean   21.000000
std     4.320494
min    15.000000
25%    19.500000
50%    22.000000
75%    23.500000
max    25.000000


In [ ]:
#Data Select + Index
grade = df[['Grade','Name']] #2D Arrays for 2 Columns Extract
grade

Grade    Name
0     A     Ali
1     F   Anjum
2     D  Shoaib
3     C    Raja

In [ ]:
row0 = df.loc[0]
row0

row1 = df.iloc[1]   #Telling by Location or Index Wise
row1

Name     Anjum
Age         21
Grade        F
Name: 1, dtype: object

In [ ]:
Maxi = df[df["Age"] < 20]  #Tells the Ages less than 20
Maxi

Name  Age Grade
3  Raja   15     C

In [ ]:
df.isnull()  #to see the Empty/Missing Data

Name    Age  Grade
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [ ]:
data = {
    "Name": ["Ali",None,"Shoaib","Raja"],  #Sets the Data
    "Age": [21,15,None,None],
    "Grade": ['A','F',None,'C']

}           #Use NaN or None for No Values

df = pd.DataFrame(data) #Make DataFrame Excel like Columns
df

Name   Age Grade
0     Ali  21.0     A
1    None  15.0     F
2  Shoaib   NaN  None
3    Raja   NaN     C

In [ ]:
df.isnull().sum()  #to see the Empty/Missing Data && alo tells the SUM

Name     1
Age      2
Grade    1
dtype: int64

In [ ]:
df.fillna(0, inplace=True)  #Fills out the Missing Values as 0
df

Name   Age Grade
0     Ali  21.0     A
1       0  15.0     F
2  Shoaib   0.0   NaN
3    Raja   0.0     C

In [ ]:
df.dropna(inplace=True) #Drop All the Missing Values
df

Name   Age Grade
0  Ali  21.0     A

In [ ]:
data = {
    "Name": ["Ali",None,"Shoaib","Raja"],  #Sets the Data
    "Age": [21,15,None,None],
    "Grade": ['A','F',None,'C'],
    'Salary' : [50000, 60000, 45000, 70000]

}

df = pd.DataFrame(data) #Make DataFrame Excel like Columns
df

Name   Age Grade  Salary
0     Ali  21.0     A   50000
1    None  15.0     F   60000
2  Shoaib   NaN  None   45000
3    Raja   NaN     C   70000

In [ ]:
# Removing a column
df.drop('Salary', axis=1, inplace=True)  #Removes the Column Name Salary on Axis 1
df

Name   Age Grade
0     Ali  21.0     A
1    None  15.0     F
2  Shoaib   NaN  None
3    Raja   NaN     C

In [ ]:
#Merge Concatenate Data Frames
my1 = pd.DataFrame ({"X" : [5,8],"Y" : [3,6]})
my2 = pd.DataFrame ({"Z" : [0,4],"W" : [4,9]})

result = pd.concat([my1,my2])
result

X    Y    Z    W
0  5.0  3.0  NaN  NaN
1  8.0  6.0  NaN  NaN
0  NaN  NaN  0.0  4.0
1  NaN  NaN  4.0  9.0

In [ ]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2'],     #Merges the Two Matrics
                     'A': ['A0', 'A1', 'A2']})
right = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                      'B': ['B0', 'B1', 'B2']})
merged = pd.merge(left, right, on='key')
print(merged)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2


In [ ]:
#Make a Groups By Checking
data = {
    "Name": ["Ali","Anjum","Shoaib","Raja"],
    "Age": [23,21,25,15],
    "Grade": ['A','F','D','C'],
    "Kills": [455,324,675,454],
    "Date": ['2024-09-20', '2024-09-21', '2024-09-22','2030-09-20']

}

df = pd.DataFrame(data)

resulx = df.groupby('Age')['Kills'].mean()
resulx

Age
15    454.0
21    324.0
23    455.0
25    675.0
Name: Kills, dtype: float64

In [ ]:
mysort = df.sort_values(by="Kills", ascending=False)
mysort

# SSort the Kills in a Decending Order

Name  Age Grade  Kills
2  Shoaib   25     D    675
0     Ali   23     A    455
3    Raja   15     C    454
1   Anjum   21     F    324

In [ ]:
#Make a Groups By Checking
data = {
    "Name": ["Ali","Anjum","Shoaib","Raja"],
    "Age": [23,21,25,15],
    "Grade": ['A','F','D','C'],
    "Kills": [455,324,675,454],
    "Date": ['2024-09-20', '2024-09-21', '2024-09-22','2030-09-20']

}

df = pd.DataFrame(data)
df


Name  Age Grade  Kills        Date
0     Ali   23     A    455  2024-09-20
1   Anjum   21     F    324  2024-09-21
2  Shoaib   25     D    675  2024-09-22
3    Raja   15     C    454  2030-09-20

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])   #Treat the Date Column as Real Date
df.set_index('Date', inplace=True)
df

Name  Age Grade  Kills
Date                                
2024-09-20     Ali   23     A    455
2024-09-21   Anjum   21     F    324
2024-09-22  Shoaib   25     D    675
2030-09-20    Raja   15     C    454

In [ ]:
data = {
    'Region': ['North', 'South', 'East', 'North', 'South', 'East'],
    'Product': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [100, 150, 200, 300, 250, 350]
}

df = pd.DataFrame(data)
pivot = df.pivot_table(values='Sales', index='Region', columns='Product', aggfunc='sum')
pivot

Product    A    B
Region           
East     200  350
North    100  300
South    250  150

[video](https://youtu.be/RhEjmHeDNoA?si=V2sUi9p20DDhxJIH)

In [ ]:
df.to_csv('New.csv') #create a CSV File & add data into it

In [ ]:
df.to_csv('New.csv', index=False) #create a CSV File & No index Shows

In [ ]:
# df.head(2)  && df.tail(3)

In [ ]:
data = {
    'Region': ['North', 'South', 'East'],
    'Product': ['A', 'B', 'A'],
    'Sales': [100, 150, 200]
}
np = pd.DataFrame(data)

In [ ]:
np['Region'][2]
np

Region Product  Sales
0  North       A    100
1  South       B    150
2   East       A    200

In [ ]:
np.index = ['1st','2nd','3rd']   #Changing the Indexes i Mean Rows Names
np

Region Product  Sales
1st  North       A    100
2nd  South       B    150
3rd   East       A    200

In [ ]:
import numpy as np

ser = pd.Series(np.random.rand(20)) #Make 1D Series in Pndas
ser

0     0.594595
1     0.595179
2     0.596244
3     0.183132
4     0.262996
5     0.456096
6     0.765515
7     0.946194
8     0.445395
9     0.476878
10    0.890077
11    0.755327
12    0.360793
13    0.554240
14    0.507052
15    0.758335
16    0.610746
17    0.850532
18    0.035670
19    0.906157
dtype: float64

In [ ]:
type(ser)

pandas.core.series.Series

In [ ]:
Newdf = pd.DataFrame(np.random.rand(500,10), index=np.arange(500))
Newdf

0         1         2         3         4         5         6  \
0    0.669673  0.330167  0.057949  0.586717  0.610290  0.232040  0.061922   
1    0.737644  0.390631  0.545201  0.847827  0.467866  0.404367  0.109393   
2    0.290208  0.066083  0.389400  0.464713  0.269392  0.084081  0.395957   
3    0.597736  0.251595  0.565536  0.155398  0.253740  0.594125  0.284840   
4    0.975481  0.410597  0.815147  0.836001  0.838435  0.460582  0.616121   
..        ...       ...       ...       ...       ...       ...       ...   
495  0.882637  0.658059  0.826544  0.041571  0.149018  0.359154  0.266591   
496  0.985105  0.088401  0.868995  0.495609  0.523227  0.224495  0.520717   
497  0.184026  0.983800  0.613375  0.598988  0.607548  0.206703  0.859092   
498  0.853150  0.555142  0.411047  0.692166  0.223814  0.379423  0.346021   
499  0.727873  0.037518  0.259989  0.265000  0.109621  0.863888  0.580523   

            7         8         9  
0    0.660345  0.005951  0.631961  
1    0.103545  0.617893  0.300790  
2    0.523414  0.102839  0.150931  
3    0.592153  0.075594  0.218120  
4    0.741846  0.907983  0.355121  
..        ...       ...       ...  
495  0.250238  0.322720  0.670368  
496  0.055600  0.513804  0.000840  
497  0.506057  0.492865  0.204116  
498  0.024685  0.727580  0.444273  
499  0.717369  0.104677  0.405254  

[500 rows x 10 columns]

In [ ]:
Newdf[0][0] = "Shahzaib" #add string in my Int DataFrame

<ipython-input-184-5d5ae9738c78>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Shahzaib' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  Newdf[0][0] = "Shahzaib"


In [ ]:
Newdf

0         1         2         3         4         5         6  \
0    Shahzaib  0.330167  0.057949  0.586717  0.610290  0.232040  0.061922   
1    0.737644  0.390631  0.545201  0.847827  0.467866  0.404367  0.109393   
2    0.290208  0.066083  0.389400  0.464713  0.269392  0.084081  0.395957   
3    0.597736  0.251595  0.565536  0.155398  0.253740  0.594125  0.284840   
4    0.975481  0.410597  0.815147  0.836001  0.838435  0.460582  0.616121   
..        ...       ...       ...       ...       ...       ...       ...   
495  0.882637  0.658059  0.826544  0.041571  0.149018  0.359154  0.266591   
496  0.985105  0.088401  0.868995  0.495609  0.523227  0.224495  0.520717   
497  0.184026  0.983800  0.613375  0.598988  0.607548  0.206703  0.859092   
498   0.85315  0.555142  0.411047  0.692166  0.223814  0.379423  0.346021   
499  0.727873  0.037518  0.259989  0.265000  0.109621  0.863888  0.580523   

            7         8         9  
0    0.660345  0.005951  0.631961  
1    0.103545  0.617893  0.300790  
2    0.523414  0.102839  0.150931  
3    0.592153  0.075594  0.218120  
4    0.741846  0.907983  0.355121  
..        ...       ...       ...  
495  0.250238  0.322720  0.670368  
496  0.055600  0.513804  0.000840  
497  0.506057  0.492865  0.204116  
498  0.024685  0.727580  0.444273  
499  0.717369  0.104677  0.405254  

[500 rows x 10 columns]

In [ ]:
Newdf.dtypes #Now Make 00 this as Object

0     object
1    float64
2    float64
3    float64
4    float64
5    float64
6    float64
7    float64
8    float64
9    float64
dtype: object

In [ ]:
Newdf.index #Get all the Index/Rows

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       490, 491, 492, 493, 494, 495, 496, 497, 498, 499],
      dtype='int64', length=500)

In [ ]:
Newdf.columns #Get all the Columns

RangeIndex(start=0, stop=10, step=1)

In [ ]:
Newdf.to_numpy() #Convert to Numpy Array

array([['Shahzaib', 0.3301673604525539, 0.057948687464871695, ...,
        0.6603447629975865, 0.005950711889279425, 0.6319608506689297],
       [0.7376439713268578, 0.39063147978142543, 0.5452009173581694, ...,
        0.10354505352427545, 0.6178925261066693, 0.3007901310810476],
       [0.2902084159814279, 0.06608312949309203, 0.3893995942312385, ...,
        0.5234141376526403, 0.10283928745608817, 0.15093093106403577],
       ...,
       [0.1840261600649662, 0.9838001757658048, 0.6133754016192676, ...,
        0.5060569788693071, 0.4928651842047863, 0.2041162404145871],
       [0.8531499322536148, 0.5551422332567068, 0.41104718085117464, ...,
        0.024684662515949807, 0.7275800487321777, 0.4442727901282414],
       [0.7278728216071614, 0.03751776703300469, 0.25998904084206054,
        ..., 0.7173688997864249, 0.1046768987610932, 0.40525353771953443]],
      dtype=object)

In [ ]:
Newdf.sort_index(axis=0,ascending=True) #Sorted out the Whole Data Ascendingly
Newdf

0         1         2         3         4         5         6  \
0    Shahzaib  0.330167  0.057949  0.586717  0.610290  0.232040  0.061922   
1    0.737644  0.390631  0.545201  0.847827  0.467866  0.404367  0.109393   
2    0.290208  0.066083  0.389400  0.464713  0.269392  0.084081  0.395957   
3    0.597736  0.251595  0.565536  0.155398  0.253740  0.594125  0.284840   
4    0.975481  0.410597  0.815147  0.836001  0.838435  0.460582  0.616121   
..        ...       ...       ...       ...       ...       ...       ...   
495  0.882637  0.658059  0.826544  0.041571  0.149018  0.359154  0.266591   
496  0.985105  0.088401  0.868995  0.495609  0.523227  0.224495  0.520717   
497  0.184026  0.983800  0.613375  0.598988  0.607548  0.206703  0.859092   
498   0.85315  0.555142  0.411047  0.692166  0.223814  0.379423  0.346021   
499  0.727873  0.037518  0.259989  0.265000  0.109621  0.863888  0.580523   

            7         8         9  
0    0.660345  0.005951  0.631961  
1    0.103545  0.617893  0.300790  
2    0.523414  0.102839  0.150931  
3    0.592153  0.075594  0.218120  
4    0.741846  0.907983  0.355121  
..        ...       ...       ...  
495  0.250238  0.322720  0.670368  
496  0.055600  0.513804  0.000840  
497  0.506057  0.492865  0.204116  
498  0.024685  0.727580  0.444273  
499  0.717369  0.104677  0.405254  

[500 rows x 10 columns]

In [ ]:
Newdf2 = Newdf.copy()    #Copy Values to Newdf2
Newdf2[0][0] = "Harrry"   #Changes Made by Harry at [0][0]
Newdf2

<ipython-input-202-6ec5b7b52208>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Newdf2[0][0] = "Harrry"


0         1         2         3         4         5         6  \
0      Harrry  0.330167  0.057949  0.586717  0.610290  0.232040  0.061922   
1    0.737644  0.390631  0.545201  0.847827  0.467866  0.404367  0.109393   
2    0.290208  0.066083  0.389400  0.464713  0.269392  0.084081  0.395957   
3    0.597736  0.251595  0.565536  0.155398  0.253740  0.594125  0.284840   
4    0.975481  0.410597  0.815147  0.836001  0.838435  0.460582  0.616121   
..        ...       ...       ...       ...       ...       ...       ...   
495  0.882637  0.658059  0.826544  0.041571  0.149018  0.359154  0.266591   
496  0.985105  0.088401  0.868995  0.495609  0.523227  0.224495  0.520717   
497  0.184026  0.983800  0.613375  0.598988  0.607548  0.206703  0.859092   
498   0.85315  0.555142  0.411047  0.692166  0.223814  0.379423  0.346021   
499  0.727873  0.037518  0.259989  0.265000  0.109621  0.863888  0.580523   

            7         8         9  
0    0.660345  0.005951  0.631961  
1    0.103545  0.617893  0.300790  
2    0.523414  0.102839  0.150931  
3    0.592153  0.075594  0.218120  
4    0.741846  0.907983  0.355121  
..        ...       ...       ...  
495  0.250238  0.322720  0.670368  
496  0.055600  0.513804  0.000840  
497  0.506057  0.492865  0.204116  
498  0.024685  0.727580  0.444273  
499  0.717369  0.104677  0.405254  

[500 rows x 10 columns]

In [ ]:
# Newdf[][] = "0.786" ❌
Newdf.loc[0,0] = "0.786"    #loc is way to Change Value
Newdf

0         1         2         3         4         5         6  \
0       0.786  0.330167  0.057949  0.586717  0.610290  0.232040  0.061922   
1    0.737644  0.390631  0.545201  0.847827  0.467866  0.404367  0.109393   
2    0.290208  0.066083  0.389400  0.464713  0.269392  0.084081  0.395957   
3    0.597736  0.251595  0.565536  0.155398  0.253740  0.594125  0.284840   
4    0.975481  0.410597  0.815147  0.836001  0.838435  0.460582  0.616121   
..        ...       ...       ...       ...       ...       ...       ...   
495  0.882637  0.658059  0.826544  0.041571  0.149018  0.359154  0.266591   
496  0.985105  0.088401  0.868995  0.495609  0.523227  0.224495  0.520717   
497  0.184026  0.983800  0.613375  0.598988  0.607548  0.206703  0.859092   
498   0.85315  0.555142  0.411047  0.692166  0.223814  0.379423  0.346021   
499  0.727873  0.037518  0.259989  0.265000  0.109621  0.863888  0.580523   

            7         8         9  
0    0.660345  0.005951  0.631961  
1    0.103545  0.617893  0.300790  
2    0.523414  0.102839  0.150931  
3    0.592153  0.075594  0.218120  
4    0.741846  0.907983  0.355121  
..        ...       ...       ...  
495  0.250238  0.322720  0.670368  
496  0.055600  0.513804  0.000840  
497  0.506057  0.492865  0.204116  
498  0.024685  0.727580  0.444273  
499  0.717369  0.104677  0.405254  

[500 rows x 10 columns]

In [ ]:
# https://youtu.be/RhEjmHeDNoA?si=d4jtHzfUQD8pj_1T&t=2114 NEXT START David YT